repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format --force-exclude --check
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types_or: [python, pyi]
        require_serial: true

